substitutions:
  name: econet-hpwh
  friendly_name: Water Heater
packages:
  esphome-econet.esphome-econet: github://esphome-econet/esphome-econet/build-yaml/econet-hpwh-esp32.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: MF1aHUCw7SZ3sxA9m+z7TQt3wHrTG4yDHqMJsB1OpF8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
